<?php

namespace Database\Seeders;

use App\Models\CarPriceSource;
use Illuminate\Database\Seeder;

class CarPriceSourceSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            // Xe 1: Mercedes-Maybach S 680
            [
                'car_id' => 1,
                'source_name' => 'Chợ Tốt Xe',
                'source_logo' => 'https://static.chotot.com/storage/default_images/pty/logo-chotot.png',
                'source_url' => 'https://xe.chotot.com/mua-ban-oto-mercedes-benz-maybach-s680',
                'car_name' => 'Mercedes-Maybach S 680 4MATIC',
                'version' => 'Bản Nhập Khẩu Tư Nhân (Lướt 5.000 km)',
                'manufacture_year' => 2024,
                'price' => 14800000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Đã qua sử dụng (Lướt 98%)',
                'warranty' => 'Bảo hành showroom tư nhân 6 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 1,
                'source_name' => 'Bonbanh.com',
                'source_logo' => 'https://bonbanh.com/assets/images/logo.png',
                'source_url' => 'https://bonbanh.com/oto/mercedes_benz-maybach_s680',
                'car_name' => 'Mercedes-Maybach S 680 4MATIC',
                'version' => 'Nhập Đức Full Option Cao Cấp',
                'manufacture_year' => 2025,
                'price' => 15650000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Mới 100% (Nhập khẩu nguyên chiếc)',
                'warranty' => 'Bảo hành đại lý 1 năm',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 1,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-mercedes-benz-maybach-s-class',
                'car_name' => 'Mercedes-Maybach S 680 4MATIC',
                'version' => 'Chính Hãng Phân Phối Việt Nam',
                'manufacture_year' => 2026,
                'price' => 16100000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100% Chính Hãng',
                'warranty' => 'Bảo hành hãng 36 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 1,
                'source_name' => 'Carmudi.vn',
                'source_logo' => 'https://static.carmudi.vn/carmudi-logo.png',
                'source_url' => 'https://www.carmudi.vn/mua-ban-oto-mercedes-benz-maybach-s-class',
                'car_name' => 'Mercedes-Maybach S 680 4MATIC',
                'version' => 'Bản Kỷ Niệm Edition 100 Giới Hạn',
                'manufacture_year' => 2025,
                'price' => 16800000000,
                'location' => 'Đà Nẵng',
                'condition_type' => 'Mới 100% Sưu tầm',
                'warranty' => 'Bảo hành 24 tháng',
                'fetched_at' => now(),
            ],

            // Xe 2: Porsche Taycan Turbo S
            [
                'car_id' => 2,
                'source_name' => 'Chợ Tốt Xe',
                'source_logo' => 'https://static.chotot.com/storage/default_images/pty/logo-chotot.png',
                'source_url' => 'https://xe.chotot.com/mua-ban-oto-porsche-taycan',
                'car_name' => 'Porsche Taycan Turbo S',
                'version' => 'Bản Điện Hiệu Năng Cao (Chạy 8.000 km)',
                'manufacture_year' => 2024,
                'price' => 8800000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Xe Lướt 95%',
                'warranty' => 'Bảo hành pin còn 6 năm',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 2,
                'source_name' => 'Carpla.vn',
                'source_logo' => 'https://carpla.vn/images/logo.svg',
                'source_url' => 'https://carpla.vn/xe/porsche-taycan-turbo-s',
                'car_name' => 'Porsche Taycan Turbo S',
                'version' => 'Gói Pin Performance Plus 93.4 kWh',
                'manufacture_year' => 2025,
                'price' => 9300000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Xe Siêu Lướt 1.500 km',
                'warranty' => 'Bảo hành chính hãng 12 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 2,
                'source_name' => 'Bonbanh.com',
                'source_logo' => 'https://bonbanh.com/assets/images/logo.png',
                'source_url' => 'https://bonbanh.com/oto/porsche_taycan',
                'car_name' => 'Porsche Taycan Turbo S',
                'version' => 'Full Carbon Interior & Ceramic Brakes',
                'manufacture_year' => 2025,
                'price' => 9600000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Mới 100% Nhập Đức',
                'warranty' => 'Bảo hành hãng 24 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 2,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-porsche-taycan',
                'car_name' => 'Porsche Taycan Turbo S',
                'version' => 'Bản Đặt Hàng Riêng Porsche Exclusive',
                'manufacture_year' => 2026,
                'price' => 9890000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100% Chính Hãng',
                'warranty' => 'Bảo hành chính hãng 3 năm + Pin 8 năm',
                'fetched_at' => now(),
            ],

            // Xe 3: BMW 740i Pure Excellence
            [
                'car_id' => 3,
                'source_name' => 'Anycar.vn',
                'source_logo' => 'https://anycar.vn/assets/images/logo.png',
                'source_url' => 'https://anycar.vn/ban-xe-bmw-7-series',
                'car_name' => 'BMW 740i Pure Excellence',
                'version' => 'Bản Tiêu Chuẩn Luxury (Lướt 6.000km)',
                'manufacture_year' => 2024,
                'price' => 5750000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Đã qua sử dụng',
                'warranty' => 'Bảo hành 6 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 3,
                'source_name' => 'Bonbanh.com',
                'source_logo' => 'https://bonbanh.com/assets/images/logo.png',
                'source_url' => 'https://bonbanh.com/oto/bmw_7_series',
                'car_name' => 'BMW 740i Pure Excellence',
                'version' => 'Màn Hình Theater Screen 31 inch 8K',
                'manufacture_year' => 2025,
                'price' => 6150000000,
                'location' => 'Đà Nẵng',
                'condition_type' => 'Mới 100%',
                'warranty' => 'Bảo hành 24 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 3,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-bmw-7-series',
                'car_name' => 'BMW 740i Pure Excellence',
                'version' => 'Chính Hãng THACO BMW Phân Phối',
                'manufacture_year' => 2026,
                'price' => 6350000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Mới 100% Chính Hãng',
                'warranty' => 'Bảo hành chính hãng 3 năm',
                'fetched_at' => now(),
            ],

            // Xe 4: Audi e-tron GT Quattro
            [
                'car_id' => 4,
                'source_name' => 'Chợ Tốt Xe',
                'source_logo' => 'https://static.chotot.com/storage/default_images/pty/logo-chotot.png',
                'source_url' => 'https://xe.chotot.com/mua-ban-oto-audi-e-tron-gt',
                'car_name' => 'Audi e-tron GT Quattro',
                'version' => 'Bản Sport Lướt Nhẹ 4.000 km',
                'manufacture_year' => 2024,
                'price' => 4850000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Đã qua sử dụng',
                'warranty' => 'Bảo hành 12 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 4,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-audi-e-tron',
                'car_name' => 'Audi e-tron GT Quattro',
                'version' => 'Chính Hãng Audi Việt Nam',
                'manufacture_year' => 2025,
                'price' => 5280000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100%',
                'warranty' => 'Bảo hành chính hãng 3 năm',
                'fetched_at' => now(),
            ],

            // Xe 5: Range Rover Autobiography LWB
            [
                'car_id' => 5,
                'source_name' => 'Bonbanh.com',
                'source_logo' => 'https://bonbanh.com/assets/images/logo.png',
                'source_url' => 'https://bonbanh.com/oto/landrover_range_rover',
                'car_name' => 'Range Rover Autobiography LWB',
                'version' => 'Trục Cơ Sở Kéo Dài 7 Chỗ Nhập Mỹ',
                'manufacture_year' => 2025,
                'price' => 11200000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Lướt 3.000 km',
                'warranty' => 'Bảo hành đại lý tư nhân 1 năm',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 5,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-land-rover-range-rover',
                'car_name' => 'Range Rover Autobiography LWB',
                'version' => 'Chính Hãng Phú Thái Mobility Phân Phối',
                'manufacture_year' => 2026,
                'price' => 11850000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100% Chính Hãng',
                'warranty' => 'Bảo hành chính hãng 3 năm + Bảo dưỡng 5 năm',
                'fetched_at' => now(),
            ],

            // Xe 6: Lexus LX 600 VIP 4 Chỗ
            [
                'car_id' => 6,
                'source_name' => 'Chợ Tốt Xe',
                'source_logo' => 'https://static.chotot.com/storage/default_images/pty/logo-chotot.png',
                'source_url' => 'https://xe.chotot.com/mua-ban-oto-lexus-lx-600',
                'car_name' => 'Lexus LX 600 VIP 4 Chỗ',
                'version' => 'Bản 4 Chỗ Ghế Thương Gia Ottoman',
                'manufacture_year' => 2024,
                'price' => 9100000000,
                'location' => 'TP. Hồ Chí Minh',
                'condition_type' => 'Đã qua sử dụng (Lướt 8.500 km)',
                'warranty' => 'Bảo hành 12 tháng',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 6,
                'source_name' => 'Bonbanh.com',
                'source_logo' => 'https://bonbanh.com/assets/images/logo.png',
                'source_url' => 'https://bonbanh.com/oto/lexus_lx600',
                'car_name' => 'Lexus LX 600 VIP 4 Chỗ',
                'version' => 'Bản Nhập Khẩu Trung Đông Full Kịch Đồ',
                'manufacture_year' => 2025,
                'price' => 9750000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100% Giao Ngay',
                'warranty' => 'Bảo hành tư nhân 2 năm',
                'fetched_at' => now(),
            ],
            [
                'car_id' => 6,
                'source_name' => 'Oto.com.vn',
                'source_logo' => 'https://oto.com.vn/images/logo-oto.svg',
                'source_url' => 'https://oto.com.vn/mua-ban-xe-lexus-lx-600',
                'car_name' => 'Lexus LX 600 VIP 4 Chỗ',
                'version' => 'Chính Hãng Lexus Việt Nam',
                'manufacture_year' => 2026,
                'price' => 9990000000,
                'location' => 'Hà Nội',
                'condition_type' => 'Mới 100% Chính Hãng (Ký Hợp Đồng Chờ)',
                'warranty' => 'Bảo hành hãng 3 năm / 100.000 km',
                'fetched_at' => now(),
            ],
        ];

        foreach ($sources as $source) {
            CarPriceSource::updateOrCreate(
                [
                    'car_id' => $source['car_id'],
                    'source_name' => $source['source_name'],
                ],
                $source
            );
        }
    }
}
